# Generated by Django 3.1.5 on 2021-02-04 18:23

from django.db import migrations, models
import django.db.models.deletion
import moderator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='moderator.customuser')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='moderator/profile/avatar/%Y/%m/%d', validators=[moderator.validators.validate_file_size, moderator.validators.empty_file]),
        ),
    ]
