# Generated by Django 3.1.5 on 2021-02-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0002_auto_20210204_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='sender',
        ),
        migrations.AddField(
            model_name='notifications',
            name='id',
            field=models.AutoField(auto_created=True, default=5, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
