# Generated by Django 3.1.5 on 2021-02-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_auto_20210205_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='sender',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR')], default='Admin', max_length=20),
            preserve_default=False,
        ),
    ]
