# Generated by Django 3.1.5 on 2021-02-11 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manger_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_from_date', models.DateTimeField(null=True)),
                ('leave_to_date', models.DateTimeField(null=True)),
                ('leave_reason', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('manager_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.managerp')),
            ],
        ),
    ]
