# Generated by Django 3.1.3 on 2021-03-04 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employee_leave_work_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0003_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_details', models.TextField(max_length=500)),
                ('task_created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('task_assign_date', models.DateTimeField(null=True)),
                ('file', models.FileField(null=True, upload_to='')),
                ('task_status', models.CharField(choices=[('Completed', 'Completed'), ('Working', 'Working'), ('Waiting Aprove', 'Waiting Aprove'), ('Incomplete close', 'Incomplete close')], default='Waiting Aprove', max_length=20)),
                ('close_task_descriptions', models.TextField(max_length=1000, null=True)),
                ('close_task_date', models.DateTimeField(null=True)),
                ('task_assign_By', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_with_intime', models.DateTimeField(null=True)),
                ('date_with_outtime', models.DateTimeField(null=True)),
                ('work_status', models.CharField(choices=[('Working', 'Working'), ('Waiting Aprove', 'Waiting Aprove'), ('wontedleave', 'wontedleave'), ('onleave', 'onleave')], default='working', max_length=20)),
                ('select_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), (' May', ' May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='', max_length=20)),
                ('emp_name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employee.employeep')),
            ],
        ),
    ]
