# Generated by Django 3.1.4 on 2021-02-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateTimeField(null=True)),
                ('leave_days', models.IntegerField()),
                ('leave_reason', models.CharField(default=True, max_length=100)),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employeep')),
            ],
        ),
    ]
