# Generated by Django 3.1.4 on 2021-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20210210_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leave',
            name='leave_reason',
            field=models.TextField(max_length=100),
        ),
    ]
