# Generated by Django 3.1.4 on 2021-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210210_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_leave',
            old_name='leave_date',
            new_name='leave_from_date',
        ),
        migrations.AddField(
            model_name='employee_leave',
            name='leave_to_date',
            field=models.DateTimeField(null=True),
        ),
    ]
