# Generated by Django 3.1.4 on 2021-02-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_remove_employee_leave_leave_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
