# Generated by Django 3.1.3 on 2021-02-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_employee_leave_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leave',
            name='leave_from_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee_leave',
            name='leave_to_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
