# Generated by Django 3.1.3 on 2021-02-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_auto_20210222_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=700)),
                ('job_location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job_apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobileno', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('Qualification', models.CharField(max_length=20)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('yearofpassing', models.IntegerField()),
                ('yearofexperience', models.FloatField(default=0.0)),
                ('resume', models.FileField(upload_to='')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.job_opening')),
            ],
        ),
    ]
