# Generated by Django 3.1.3 on 2021-02-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_job_apply_job_opening'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_opening',
            new_name='job_opening_model',
        ),
    ]
