# Generated by Django 3.1.3 on 2021-02-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20210223_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_apply',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.AlterField(
            model_name='job_apply',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
