# Generated by Django 3.1.3 on 2021-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20210226_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_opening_model',
            name='job_posting',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
