# Generated by Django 3.1.3 on 2021-03-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_auto_20210302_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_leave',
            name='work_status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], default='empty', max_length=20),
        ),
    ]
