# Generated by Django 3.1.3 on 2021-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening',
            name='eligibility',
            field=models.CharField(default='Degree', max_length=50),
        ),
    ]
