# Generated by Django 3.1.3 on 2021-03-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_auto_20210225_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
