# Generated by Django 3.1.3 on 2021-03-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='opening',
            name='job_location',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
